const actionType = {
  GET_MOVIE: 'GET_MOVIE',
  SEARCH_MOVIE: 'SEARCH_MOVIE',
  GET_MOVIE_DETAIL: 'GET_MOVIE_DETAIL',
  ADD_WATCHLIST: 'ADD_WATCHLIST',
  DELETE_WATCHLIST: 'DELETE_WATCHLIST',
  GET_WATCHLIST: 'GET_WATCHLIST',
};

export default actionType;
